"""
Django settings for machakos_aidsttup project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see:
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# ======================================================
# ENVIRONMENT CONFIGURATION
# ======================================================

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'
BASE_DIR = Path(__file__).resolve().parent.parent


# ======================================================
# SECURITY SETTINGS
# ======================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-dev-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Hosts/domain names that this Django site can serve
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Security middleware settings for production
if not DEBUG:
    # Force HTTPS in production
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# ======================================================
# APPLICATION DEFINITION
# ======================================================

INSTALLED_APPS = [
    # Django core applications
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Django GIS (Geographic Information Systems) - Required for spatial data
    'django.contrib.gis',
    
    # Third party applications
    'leaflet',              # Interactive maps
    'crispy_forms',         # Form styling
    'crispy_bootstrap5',    # Bootstrap 5 template pack for crispy forms
    'rest_framework',       # API framework
    'corsheaders',          # For handling CORS (Cross-Origin Resource Sharing)
    
    # Local applications
    'farms',                # Farm management and data
    'insurance',            # Insurance-related functionality
    'satellite',            # Satellite data processing and analysis
]

MIDDLEWARE = [
    # Security middleware
    'django.middleware.security.SecurityMiddleware',
    
    # Whitenoise for static files in production
    'whitenoise.middleware.WhiteNoiseMiddleware',
    
    # CORS headers for API requests
    'corsheaders.middleware.CorsMiddleware',
    
    # Django session middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    # Common middleware
    'django.middleware.common.CommonMiddleware',
    
    # CSRF protection
    'django.middleware.csrf.CsrfViewMiddleware',
    
    # Authentication middleware
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    
    # Message middleware
    'django.contrib.messages.middleware.MessageMiddleware',
    
    # Clickjacking protection
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Root URL configuration
ROOT_URLCONF = 'machakos_aidsttup.urls'

# Template configuration
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Project-level templates directory
        'APP_DIRS': True,  # Look for templates in app directories
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                # Custom context processors can be added here
            ],
        },
    },
]

# WSGI application
WSGI_APPLICATION = 'machakos_aidsttup.wsgi.application'


# ======================================================
# DATABASE CONFIGURATION
# ======================================================

# Primary database configuration using PostgreSQL with PostGIS extension
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.getenv('DB_NAME', 'machakos_drought'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'CONN_MAX_AGE': 600,  # Database connection persistence
    }
}

# Use DATABASE_URL environment variable if available (for deployment platforms like Heroku, Railway, etc.)
if 'DATABASE_URL' in os.environ:
    DATABASES['default'] = dj_database_url.config(
        conn_max_age=600,
        conn_health_checks=True,
    )
    DATABASES['default']['ENGINE'] = 'django.contrib.gis.db.backends.postgis'


# ======================================================
# PASSWORD VALIDATION
# ======================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,  # Minimum password length
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ======================================================
# INTERNATIONALIZATION
# ======================================================

# Language settings
LANGUAGE_CODE = 'en-us'  # English (United States)

# Time zone - Set to Nairobi, Kenya for local time
TIME_ZONE = 'Africa/Nairobi'

# Enable internationalization
USE_I18N = True

# Enable localization
USE_L10N = True

# Use timezone-aware datetimes
USE_TZ = True


# ======================================================
# STATIC FILES (CSS, JavaScript, Images)
# ======================================================

STATIC_URL = 'static/'  # URL prefix for static files

# Directory where collectstatic will collect static files for deployment
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional locations of static files
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Project-level static directory
]

# Whitenoise compression and caching
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# ======================================================
# MEDIA FILES (User uploaded files)
# ======================================================

MEDIA_URL = '/media/'  # URL prefix for media files
MEDIA_ROOT = BASE_DIR / 'media'  # Directory where media files are stored


# ======================================================
# LEAFLET CONFIGURATION (Interactive Maps)
# ======================================================

LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (-1.52, 37.26),  # Machakos County center coordinates
    'DEFAULT_ZOOM': 10,  # Initial zoom level
    'MIN_ZOOM': 3,  # Minimum zoom level allowed
    'MAX_ZOOM': 18,  # Maximum zoom level allowed
    'ATTRIBUTION_PREFIX': 'Machakos Drought Monitoring System',
    'TILES': [('OpenStreetMap', 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        'attribution': '&copy; OpenStreetMap contributors'
    })],
    'PLUGINS': {
        'gesturehandling': {
            'css': 'https://unpkg.com/leaflet-gesture-handling/dist/leaflet-gesture-handling.min.css',
            'js': 'https://unpkg.com/leaflet-gesture-handling/dist/leaflet-gesture-handling.min.js',
            'auto': True,  # Automatically enable gesture handling
        }
    }
}


# ======================================================
# CRISPY FORMS CONFIGURATION
# ======================================================

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# ======================================================
# REST FRAMEWORK CONFIGURATION (API)
# ======================================================

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,  # Default page size for paginated endpoints
}


# ======================================================
# CORS CONFIGURATION (Cross-Origin Resource Sharing)
# ======================================================

# Configure CORS settings for API access
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React development server
    "http://127.0.0.1:3000",
]

# Allow credentials (cookies, authorization headers) to be included
CORS_ALLOW_CREDENTIALS = True


# ======================================================
# GOOGLE EARTH ENGINE CONFIGURATION
# ======================================================

GEE_SERVICE_ACCOUNT = os.getenv('GEE_SERVICE_ACCOUNT')
GEE_PRIVATE_KEY = os.getenv('GEE_PRIVATE_KEY')


# ======================================================
# AUTHENTICATION & LOGIN CONFIGURATION
# ======================================================

# URL where users are redirected after login
LOGIN_REDIRECT_URL = '/dashboard/'

# URL where users are redirected after logout
LOGOUT_REDIRECT_URL = '/'

# URL for login page
LOGIN_URL = '/accounts/login/'

# Password hashers (in order of preference)
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]


# ======================================================
# SESSION CONFIGURATION
# ======================================================

# Session cookie age (2 weeks in seconds)
SESSION_COOKIE_AGE = 1209600

# Save session on every request
SESSION_SAVE_EVERY_REQUEST = True

# Expire session when browser closes
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# ======================================================
# EMAIL CONFIGURATION
# ======================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Machakos Drought System <noreply@machakosdrought.org>')


# ======================================================
# LOGGING CONFIGURATION
# ======================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': True,
        },
        'farms': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'satellite': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# ======================================================
# CACHE CONFIGURATION
# ======================================================

# Default cache (can be replaced with Redis or Memcached in production)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Cache timeout in seconds (5 minutes for general caching)
CACHE_TIMEOUT = 300


# ======================================================
# FILE UPLOAD CONFIGURATION
# ======================================================

# Maximum size of request data (10MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

# Maximum size of file uploads (10MB)
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

# Maximum number of files that can be uploaded in a single request
FILE_UPLOAD_MAX_NUMBER_FILES = 100


# ======================================================
# DEFAULT PRIMARY KEY FIELD TYPE
# ======================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ======================================================
# CUSTOM SETTINGS FOR DROUGHT MONITORING SYSTEM
# ======================================================

# System-specific configuration
DROUGHT_THRESHOLD = 0.3  # NDVI threshold for drought classification (0-1 scale)
MIN_FARM_SIZE = 0.1  # Minimum farm size in hectares
MAX_FARM_SIZE = 100  # Maximum farm size in hectares

# API keys for external services
WEATHER_API_KEY = os.getenv('WEATHER_API_KEY', '')
SATELLITE_API_KEY = os.getenv('SATELLITE_API_KEY', '')

# System name and version
SYSTEM_NAME = "Machakos Drought Monitoring System"
SYSTEM_VERSION = "1.0.0"
SYSTEM_CONTACT_EMAIL = "support@machakosdrought.org"