# Generated by Django 6.0 on 2025-12-05 03:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('county_code', models.CharField(max_length=50, unique=True)),
                ('subcounty', models.CharField(max_length=100)),
                ('subcounty_code', models.CharField(max_length=50, unique=True)),
                ('geometry_geojson', models.TextField(blank=True, null=True)),
                ('centroid_lat', models.FloatField(blank=True, null=True)),
                ('centroid_lng', models.FloatField(blank=True, null=True)),
                ('avg_rainfall', models.FloatField(blank=True, help_text='Average annual rainfall in mm', null=True)),
                ('soil_type', models.CharField(blank=True, max_length=100)),
                ('elevation', models.FloatField(blank=True, help_text='Average elevation in meters', null=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'ordering': ['county', 'subcounty'],
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('village', models.CharField(max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('mpesa_number', models.CharField(blank=True, max_length=20)),
                ('subcounty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='farms.county')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('osm_id', models.CharField(blank=True, help_text='Original OSM ID if from OpenStreetMap', max_length=100)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('geometry_geojson', models.TextField(blank=True, null=True)),
                ('centroid_lat', models.FloatField()),
                ('centroid_lng', models.FloatField()),
                ('area_ha', models.FloatField(help_text='Area in hectares', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('crop_type', models.CharField(default='maize', max_length=100)),
                ('crop_variety', models.CharField(blank=True, max_length=100)),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('landuse', models.CharField(blank=True, max_length=100)),
                ('soil_quality', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=50)),
                ('irrigation', models.BooleanField(default=False)),
                ('irrigation_type', models.CharField(blank=True, choices=[('drip', 'Drip'), ('sprinkler', 'Sprinkler'), ('flood', 'Flood'), ('none', 'None')], max_length=50)),
                ('operator', models.CharField(blank=True, max_length=200)),
                ('cooperative', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('gee_asset_path', models.CharField(blank=True, help_text='Path in GEE Assets where farm polygon is stored', max_length=500)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='farms.county')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='farms.farmer')),
            ],
            options={
                'ordering': ['farm_id'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=50, unique=True)),
                ('coverage_start', models.DateField()),
                ('coverage_end', models.DateField()),
                ('sum_insured', models.DecimalField(decimal_places=2, help_text='Total insured amount in KES', max_digits=12)),
                ('premium_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('premium_rate', models.FloatField(help_text='Premium as percentage of sum insured')),
                ('trigger_threshold_ndvi', models.FloatField(default=0.3)),
                ('trigger_threshold_rainfall', models.FloatField(default=50, help_text='mm per month')),
                ('payout_rate', models.FloatField(default=1.0, help_text='Payout as fraction of sum insured')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('claimed', 'Claim Made')], default='active', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policy', to='farms.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='farms.farmer')),
            ],
            options={
                'verbose_name_plural': 'Insurance Policies',
                'ordering': ['-coverage_start'],
            },
        ),
        migrations.CreateModel(
            name='SatelliteAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('ndvi', models.FloatField(blank=True, help_text='Normalized Difference Vegetation Index', null=True)),
                ('evi', models.FloatField(blank=True, help_text='Enhanced Vegetation Index', null=True)),
                ('ndmi', models.FloatField(blank=True, help_text='Normalized Difference Moisture Index', null=True)),
                ('savi', models.FloatField(blank=True, help_text='Soil Adjusted Vegetation Index', null=True)),
                ('ndre', models.FloatField(blank=True, help_text='Normalized Difference Red Edge', null=True)),
                ('rainfall_mm', models.FloatField(blank=True, help_text='Total rainfall in mm for period', null=True)),
                ('vegetation_health', models.CharField(blank=True, choices=[('excellent', 'Excellent (NDVI > 0.6)'), ('good', 'Good (NDVI 0.4-0.6)'), ('moderate', 'Moderate (NDVI 0.3-0.4)'), ('poor', 'Poor (NDVI 0.2-0.3)'), ('critical', 'Critical (NDVI < 0.2)')], max_length=20)),
                ('moisture_stress', models.CharField(blank=True, choices=[('none', 'No Stress'), ('mild', 'Mild Stress'), ('moderate', 'Moderate Stress'), ('severe', 'Severe Stress')], max_length=20)),
                ('cloud_cover_percentage', models.FloatField(blank=True, null=True)),
                ('image_count', models.IntegerField(default=0)),
                ('analysis_timestamp', models.DateTimeField(auto_now_add=True)),
                ('drought_risk_level', models.CharField(blank=True, choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('severe', 'Severe Risk')], max_length=20)),
                ('insurance_triggered', models.BooleanField(default=False)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='farms.farm')),
            ],
            options={
                'verbose_name_plural': 'Satellite Analyses',
                'ordering': ['-analysis_date', 'farm'],
                'unique_together': {('farm', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=50, unique=True)),
                ('trigger_date', models.DateField()),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('ndvi_value', models.FloatField(blank=True, null=True)),
                ('rainfall_value', models.FloatField(blank=True, null=True)),
                ('satellite_image_url', models.URLField(blank=True)),
                ('field_assessment_report', models.FileField(blank=True, upload_to='claim_reports/')),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='farms.farm')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='farms.insurancepolicy')),
                ('triggered_by_analysis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='farms.satelliteanalysis')),
            ],
            options={
                'ordering': ['-trigger_date'],
            },
        ),
    ]
